[package]
name = "custom_panel"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "custom_panel.rs"

[dependencies]
gpui.workspace = true
ui.workspace = true
workspace.workspace = true
anyhow.workspace = true
i18n.workspace = true